### ISSUE TITLE
Missing a few attributes

### ISSUE THREAD

**Issue by bdf0506** [mww012/ha_customcomponents#1]
This component pulls in most of the API from Infinitive, but there are a few missing. Within HA you can pretty easily pull this data in via a JSON sensor, but would make more sense if the few missing api calls can be brought into the code, so that it can be called with a template sensor instead.

In particular these are missing:

* /api/zone/1/config/outdoorTemp
* /api/airhandler/auxHeat
* /api/heatpump/coilTemp
* /api/heatpump/outsideTemp (might be the same as /api/zone/1/config/outdoorTemp)

**Comment by mww012** [comment]
Resolved in merged PR from @pfiggins
